controller_frequency: 18.0
planner_patience: 2.0
controller_patience: 2.0

TrajectoryPlannerROS:
  min_vel_x: 0.1
  min_vel_theta: 0.2
  min_in_place_vel_theta: 0.2

  holonomic_robot: false
  latch_xy_goal_tolerance: true #false

