obstacle_range: 2.5
raytrace_range: 3.0
max_obstacle_height: 0.5

#footprint: [[-0.3, -0.35], [-0.3, 0.35], [0.25,0.35], [0.35,0.0],[0.25,-0.35]]
robot_radius: 0.35
#footprint_padding: 0.01

inflation_radius: 0.35

observation_sources: scan
scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true}
