obstacle_range: 2.5
raytrace_range: 3.0
max_obstacle_height: 0.5

#footprint: [[-0.3,0.0], [-0.2,0.3], [0.2,0.3], [0.3,0.0], [0.2,-0.3], [-0.2,-0.3]]
robot_radius: 0.35
footprint_padding: 0.01

#inflation_radius: 0.5

observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
